### ISSUE TITLE
Support for Angular 1.4

### ISSUE THREAD

**Issue by michaelkrone** [fmquaglia/ngOrderObjectBy#10]
When installing angular-order-object-by via bower, in a project that uses the latest Angular 1.4 branch, the following message appears:

    angular-order-object-by#1.1.1 depends on angular#~1.3.11 which resolved to angular#1.3.18

All tests pass for Angular 1.4, and there are no problems when using it in a 1.4 environment. Maybe one could update the bower.json's angular versions to 

    "angular": "^1.3.x-1.5"

**Comment by fmquaglia** [comment]
@michaelkrone Can you make a PR for this? I'll merge it gladly. Please make sure that it passes the tests.

**Comment by michaelkrone** [comment]
All tests pass nicely.
