### ISSUE TITLE
Tag for Bower

### ISSUE THREAD

**Issue by Maaack** [fmquaglia/ngOrderObjectBy#18]
Attempting to install version 1.3.0 results in the following message:
```
bower angular-order-object-by#1.3.0     ENORESTARGET No tag found that was able to satisfy 1.3.0

Additional error details:
Available versions in git://github.com/fmquaglia/ngOrderObjectBy.git: 1.2.1, 1.1.1, 1.1.0, 1.0.0
```

Could you add a new tag for the 1.3.0 release? Thanks!

**Comment by fmquaglia** [comment]
Hello @Maaack thanks for the heads up. 
It is my fault, I tagged it as --```1.3```-- rather than ```1.3.0```.

You should be able to pick it up now:

![1.3.0](http://d.pr/i/1juFg+)

**Comment by Maaack** [comment]
Confirmed, it 1.3.0 installed with bower. Thanks @fmquaglia

**Comment by fmquaglia** [comment]
Great @Maaack ! :smile: :+1:
